travis:
  secure:
    BINSTAR_TOKEN: VuGBlEwCQ7KEcdJvrnixAVNh8uCLjG+GJ/eHc47Fakftk0Ha1rY/LW0ahaCyVsllNmYyz7el8UB7qoV883RY3ubMLhGa39s30riq+birOPy8h4QGyhuhBPevywJPe9pA2Der1qv2HJUkqEHTdmrUbRYfDPvwDUOSyeH3csFs9+GIdV7lAZQiQ2HrwD+8J3gUE1VeJXP31DvXLr7SeaY+0rdg9+BlDmu09w71j8PQ+eReet19Zi/Z+RgVXdw3cfQdsRhB+TTgtYpNdIDLPbgNooK5y4ueSLmpqESo2XHIbKlpe6Pguk5DuLztZGUKyqCI/6DVXKiKyU7q1juH5/jPi66NFrz3MvdzzHmqJoZhKeT8P2X8fHpnU8JpAl78fphwTmuK/v4KUHnMzEWMwEAP/wn2HotFwR88kLKR5LCcCGzKkB9iyshjsqli3/YVlmq+QbRv2gmlcdIXxSJCQPYpMrMVTy6sxHI5YfAVojMM4lq7MoakI+O58/eE7CverFyDDQ3zQxMl1A4CgFgJH4PWg/BFS2aP2oiF6SBGDGYrDFSYB/qYIZUPHCzPKvHRp2IEHqHbeJHSByiDOjHksRFti0ZZTqg7NHHaLad2VWfKA59ahHEuF75/1L0xa+dGSfZ1hcYMOICXacvqSNWY/lVqAIPwFXuOD/QX6ULjTOz7gzI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
