travis:
  secure:
    BINSTAR_TOKEN: UMN1g40q4pFUQFakkCVyCvGVwsbTjiF2CGLn9GpBtH3oj4a8/1RfUHM52f1pd92Q/cwJm2BBiIMZeqr29BINMyu36dwUnkf+wS98sRr7xh3X1bkkC/yMQvzuRJxLnWsbaGik0Z+au5YKS0qYPFrEP0GZ0WegFfsVNYJRyRCX8wwMMB+34genaA4y/tZSIrN+Db0XkxeOWbDB0sOYfBDxXLv3ersW/7j6HF3ES+3eve1r2np3xGOnqtMWfzw2IgmQcgLNuVE+1gir+ERY9XrDI4a7OgTtL2th4/LSMwfWlY7XvrGLcFGl/6AY2YOTF3gogBAfv+8S4BGwg2XBHrBDd97TkQj4razbTa0+6r3H31zBeKHQg4SwG04yi0RGeYQj1nm8nB1PPCoyx3pbz5857cz+7cTlpWVTbuVNH+yE88A345bSbs5VrBVmS7Ebh7zsnhEiZNY2oxAVeUFD4re9aEyIFKbgUj/IvqH/wY2V0ZFbp04574Xuxx1uYRBuHNvirKNhNTRynkCcfDT6OLbrSKolY4bZHK1sA5kqXFX7hE/f6hpIA3maEK7v9m15SIYxZfnWPBSTS1xlK6UPGQXyer5vOIx9B7Ehps+i5ghD0U9tc/aOpibNxc+UoM/CRhNcozWGGOaJLQLO06gu45+B3xoW60i82DvOejTev1WnSA8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
